services:
  - type: web
    name: haircloud-app
    env: php
    plan: free
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: cp .env.example .env && php artisan key:generate && php artisan migrate --seed --force && heroku-php-apache2 public/
    envVars:
      - key: APP_NAME
        value: HairCloud
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: haircloud-db
          property: connectionString

databases:
  - name: haircloud-db
    databaseName: beauty_salon
    user: haircloud_user
    plan: free
